#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "🧪 Running Cypress tests before push..."

npx cypress run

if [ $? -ne 0 ]; then
  echo "❌ Tests failed. Push aborted."
  exit 1
else
  echo "✅ All tests passed. Proceeding with push."
fi
